#on: push
jobs:
    build-windows:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [ windows-2016, windows-latest ]
      steps:
        - uses: actions/checkout@v1
        - uses: DeLaGuardo/setup-graalvm@master
          with:
            graalvm-version: '21.0.0.java11'
        - run: java -version
        - name: Set up Visual C Build Tools Workload for Visual Studio 2017 Build Tools
          run: |
            choco install visualstudio2017-workload-vctools
        - name: Install native-image component
          run: |
            gu.cmd install native-image
        - name: compile runmpv.exe
          shell: cmd
          run: |
            call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
            ./build.bat
